#Makefile previsto per il progetto GAME OF LIFE
#written by Riccardo Fontanini
OBJECTS=

#compiler
CC=gcc
#general flags
CFLAGS= -g -w

NAMEFILE = main.c
PROGRAM_NAME = ca


ca: 

	gcc $(NAMEFILE) -o ca.out -std=gnu99
	@echo " "
	@echo "Compilazione completata! il file si trova nella cartella build/linux!"
	@echo " "